

theme = [
    #"github.com/bep/hugotestmods/myassets",
    #"github.com/bep/hugotestmods/myshortcodes",
     "github.com/bep/hugotestmods/myv2/v2",
    #"github.com/bep/hugotestmods/mypartials",
   
    
    "github.com/bep/hugo-fresh",
    #"github.com/jeblister/kube",
    #"github.com/spf13/hyde",

]

# hugo mod get github.com/bep/hugotestmods/mypartials






baseURL = "http://example.org/"
languageCode = "en-us"
title = "My Modular Hugo Site"


disableKinds = [
    "taxonomyTerm"
]


[params]
icon = "doc-sync"