
baseURL = "http://example.org/"
languageCode = "en-us"
title = "My Modular Hugo Site"
disableKinds = [
    "taxonomyTerm"
]

[params]
icon = "doc-sync"

[module]
[[module.mounts]]
source="content"
target="content"
[[module.imports]]
path="github.com/bep/hugotestmods/mymounts"
[[module.imports.mounts]]
source="myassets/subfolder"
target="assets/images"
[[module.imports.mounts]]
source="mydata/subfolder"
target="data/datakey"
[[module.imports]]
path="github.com/bep/hugotestmods/mypartials"
[[module.imports]]
path="github.com/bep/hugo-fresh"
[[module.imports]]
path="in-themesdir"
